import { readFileSync, writeFileSync } from 'node:fs';
import { resolve } from 'node:path';
import { canonicalTier, entryPoints, packageExports } from './tier-metadata.mjs';

const root = resolve(import.meta.dirname, '..');
const write = process.argv.includes('--write');
const stale = [];
const commonExports = [
	"export type { DecimalLike, DecimalValue, DecimalValueIterable } from './DecimalBase.js';",
	"export type { DecimalConfig, DecimalConfigInput } from './config/DecimalConfig.js';",
	"export type { ModuloMode, RoundingMode } from './config/RoundingModes.js';",
	"export type { DecimalLimits } from './DecimalLimits.js';",
	"export { DecimalError, type DecimalErrorCode } from './errors.js';"
];

function sync(file, transform)
{
	const path = resolve(root, file);
	const current = readFileSync(path, 'utf8');
	const expected = transform(current);
	if (current === expected) return;
	if (write) writeFileSync(path, expected);
	else stale.push(file);
}

sync('package.json', text => {
	const manifest = JSON.parse(text);
	manifest.exports = packageExports;
	manifest.types = packageExports['.'].types;
	return JSON.stringify(manifest, null, '\t') + '\n';
});

sync('typedoc.json', text => {
	const config = JSON.parse(text);
	config.entryPoints = entryPoints.map(entry => entry.source);
	return JSON.stringify(config, null, '\t') + '\n';
});

for (const entry of entryPoints)
{
	sync(entry.source, () => {
		const tier = entry.tier;
		const comment = `/**\n * ${tier.description}.\n *\n * @packageDocumentation\n * Generated by pnpm run sync:tiers from scripts/tier-metadata.mjs.\n */\n`;
		if (entry.id === 'root') return comment + `export * from './${canonicalTier.id}.js';\n`;
		const names = [
			`${tier.className} as Decimal`,
			`type ${tier.className}Constructor as DecimalConstructor`
		];
		if (tier.rank > 0) names.push(`type ${tier.className}Fraction as DecimalFraction`);
		if (tier === canonicalTier) names.push(tier.className, `type ${tier.className}Constructor`);
		return comment + `export {\n\t${names.join(',\n\t')}\n} from './${tier.className}.js';\n` + commonExports.join('\n') + '\n';
	});
}

sync('src/Decimal.ts', () => [
	'/** Compatibility re-exports. Generated by pnpm run sync:tiers. */',
	'export {',
	`\t${canonicalTier.className} as Decimal,`,
	`\ttype ${canonicalTier.className}Constructor as DecimalConstructor,`,
	`\ttype ${canonicalTier.className}Fraction as DecimalFraction`,
	`} from './${canonicalTier.className}.js';`,
	commonExports[0], ''
].join('\n'));

if (stale.length) throw new Error(`Tier metadata is out of sync: ${stale.join(', ')}. Run pnpm run sync:tiers.`);
console.log(write ? 'Tier metadata synchronized.' : 'Tier metadata is synchronized.');
