/**
 * Core plus arithmetic, rounding, shifting, and fractions.
 *
 * @packageDocumentation
 * Generated by pnpm run sync:tiers from scripts/tier-metadata.mjs.
 */
export {
	ArithmeticDecimal as Decimal,
	type ArithmeticDecimalConstructor as DecimalConstructor,
	type ArithmeticDecimalFraction as DecimalFraction
} from './ArithmeticDecimal.js';
export type { DecimalLike, DecimalValue, DecimalValueIterable } from './DecimalBase.js';
export type { DecimalConfig, DecimalConfigInput } from './config/DecimalConfig.js';
export type { ModuloMode, RoundingMode } from './config/RoundingModes.js';
export type { DecimalLimits } from './DecimalLimits.js';
export { DecimalError, type DecimalErrorCode } from './errors.js';
