/**
 * Representation, parsing, comparison, predicates, and string/number formatting.
 *
 * @packageDocumentation
 * Generated by pnpm run sync:tiers from scripts/tier-metadata.mjs.
 */
export {
	CoreDecimal as Decimal,
	type CoreDecimalConstructor as DecimalConstructor
} from './CoreDecimal.js';
export type { DecimalLike, DecimalValue, DecimalValueIterable } from './DecimalBase.js';
export type { DecimalConfig, DecimalConfigInput } from './config/DecimalConfig.js';
export type { ModuloMode, RoundingMode } from './config/RoundingModes.js';
export type { DecimalLimits } from './DecimalLimits.js';
export { DecimalError, type DecimalErrorCode } from './errors.js';
