/** Compatibility re-exports. Generated by pnpm run sync:tiers. */
export {
	ScientificDecimal as Decimal,
	type ScientificDecimalConstructor as DecimalConstructor,
	type ScientificDecimalFraction as DecimalFraction
} from './ScientificDecimal.js';
export type { DecimalLike, DecimalValue, DecimalValueIterable } from './DecimalBase.js';
