/**
 * Arithmetic plus powers, logarithms, trigonometry, `PI`, and `atan2` (the complete API).
 *
 * @packageDocumentation
 * Generated by pnpm run sync:tiers from scripts/tier-metadata.mjs.
 */
export * from './scientific.js';
