/**
 * Arithmetic plus powers, logarithms, trigonometry, `PI`, and `atan2` (the complete API).
 *
 * @packageDocumentation
 * Generated by pnpm run sync:tiers from scripts/tier-metadata.mjs.
 */
export {
	ScientificDecimal as Decimal,
	type ScientificDecimalConstructor as DecimalConstructor,
	type ScientificDecimalFraction as DecimalFraction,
	ScientificDecimal,
	type ScientificDecimalConstructor
} from './ScientificDecimal.js';
export type { DecimalLike, DecimalValue, DecimalValueIterable } from './DecimalBase.js';
export type { DecimalConfig, DecimalConfigInput } from './config/DecimalConfig.js';
export type { ModuloMode, RoundingMode } from './config/RoundingModes.js';
export type { DecimalLimits } from './DecimalLimits.js';
export { DecimalError, type DecimalErrorCode } from './errors.js';
